-- Flowable 节点动作配置表
CREATE TABLE IF NOT EXISTS `wf_node_action` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `model_id` bigint(20) DEFAULT NULL COMMENT '模型ID',
    `model_key` varchar(64) DEFAULT NULL COMMENT '模型标识',
    `model_version` int(11) DEFAULT NULL COMMENT '模型版本',
    `node_id` varchar(64) DEFAULT NULL COMMENT '节点ID',
    `node_name` varchar(255) DEFAULT NULL COMMENT '节点名称',
    `event_type` varchar(32) DEFAULT NULL COMMENT '事件类型：create-创建，complete-完成，delete-删除',
    `action_type` varchar(32) DEFAULT NULL COMMENT '动作类型：approval-审批，notification-通知，service-服务调用，script-脚本执行',
    `action_config` text COMMENT '动作配置JSON',
    `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用：0-禁用，1-启用',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志：0-正常，1-删除',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_model_id` (`model_id`),
    KEY `idx_node_id` (`node_id`),
    KEY `idx_event_type` (`event_type`),
    KEY `idx_action_type` (`action_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Flowable节点动作配置表';

-- 流程实例扩展表
CREATE TABLE IF NOT EXISTS `wf_process_ext` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `process_instance_id` varchar(64) NOT NULL COMMENT '流程实例ID',
    `process_definition_key` varchar(64) DEFAULT NULL COMMENT '流程定义Key',
    `process_definition_name` varchar(255) DEFAULT NULL COMMENT '流程定义名称',
    `process_definition_version` int(11) DEFAULT NULL COMMENT '流程定义版本',
    `business_key` varchar(255) DEFAULT NULL COMMENT '业务Key',
    `start_user` varchar(64) DEFAULT NULL COMMENT '发起人',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `duration` bigint(20) DEFAULT NULL COMMENT '持续时间(毫秒)',
    `status` varchar(32) DEFAULT 'running' COMMENT '状态：running-运行中，completed-已完成，suspended-已挂起，terminated-已终止',
    `variables` text COMMENT '流程变量JSON',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志：0-正常，1-删除',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_process_instance_id` (`process_instance_id`),
    KEY `idx_business_key` (`business_key`),
    KEY `idx_start_user` (`start_user`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例扩展表';

-- 任务扩展表
CREATE TABLE IF NOT EXISTS `wf_task_ext` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id` varchar(64) NOT NULL COMMENT '任务ID',
    `task_name` varchar(255) DEFAULT NULL COMMENT '任务名称',
    `task_definition_key` varchar(64) DEFAULT NULL COMMENT '任务定义Key',
    `process_instance_id` varchar(64) NOT NULL COMMENT '流程实例ID',
    `process_definition_id` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
    `assignee` varchar(64) DEFAULT NULL COMMENT '处理人',
    `candidate_groups` varchar(500) DEFAULT NULL COMMENT '候选组',
    `candidate_users` varchar(500) DEFAULT NULL COMMENT '候选用户',
    `priority` int(11) DEFAULT '50' COMMENT '优先级',
    `due_date` datetime DEFAULT NULL COMMENT '到期时间',
    `start_time` datetime DEFAULT NULL COMMENT '开始时间',
    `end_time` datetime DEFAULT NULL COMMENT '结束时间',
    `duration` bigint(20) DEFAULT NULL COMMENT '持续时间(毫秒)',
    `status` varchar(32) DEFAULT 'active' COMMENT '状态：active-活动，completed-已完成，deleted-已删除',
    `variables` text COMMENT '任务变量JSON',
    `action_config` text COMMENT '节点动作配置JSON',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志：0-正常，1-删除',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_id` (`task_id`),
    KEY `idx_process_instance_id` (`process_instance_id`),
    KEY `idx_assignee` (`assignee`),
    KEY `idx_task_definition_key` (`task_definition_key`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务扩展表';

-- 部署记录表
CREATE TABLE IF NOT EXISTS `wf_deployment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `deployment_id` varchar(64) NOT NULL COMMENT '部署ID',
    `name` varchar(255) DEFAULT NULL COMMENT '部署名称',
    `category` varchar(64) DEFAULT NULL COMMENT '分类',
    `key` varchar(64) DEFAULT NULL COMMENT '流程Key',
    `tenant_id` varchar(64) DEFAULT '' COMMENT '租户ID',
    `deployment_time` datetime DEFAULT NULL COMMENT '部署时间',
    `engine_version` varchar(32) DEFAULT NULL COMMENT '引擎版本',
    `resource_name` varchar(255) DEFAULT NULL COMMENT '资源名称',
    `diagram_resource_name` varchar(255) DEFAULT NULL COMMENT '图片资源名称',
    `is_latest_version` tinyint(1) DEFAULT '1' COMMENT '是否最新版本',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志：0-正常，1-删除',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_deployment_id` (`deployment_id`),
    KEY `idx_key` (`key`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部署记录表';

-- 模型表
CREATE TABLE IF NOT EXISTS `wf_model` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `model_id` varchar(64) NOT NULL COMMENT '模型ID',
    `name` varchar(255) DEFAULT NULL COMMENT '模型名称',
    `key` varchar(64) DEFAULT NULL COMMENT '模型Key',
    `category` varchar(64) DEFAULT NULL COMMENT '分类',
    `version` int(11) DEFAULT '1' COMMENT '版本',
    `meta_info` text COMMENT '元信息JSON',
    `bpmn_xml` longtext COMMENT 'BPMN XML内容',
    `svg_xml` text COMMENT 'SVG图片内容',
    `deployment_id` varchar(64) DEFAULT NULL COMMENT '部署ID',
    `tenant_id` varchar(64) DEFAULT '' COMMENT '租户ID',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint(1) DEFAULT '0' COMMENT '删除标志：0-正常，1-删除',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_model_id` (`model_id`),
    KEY `idx_key` (`key`),
    KEY `idx_category` (`category`),
    KEY `idx_deployment_id` (`deployment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程模型表';
